const achievementStyles=document.createElement('style');
achievementStyles.textContent=`
.achievements-entry{margin-top:14px;border:0;border-radius:22px;padding:20px 24px;width:100%;display:flex;align-items:center;justify-content:space-between;gap:18px;text-align:left;background:linear-gradient(110deg,#ffbd3f,#ff7967);color:#49300b;box-shadow:0 14px 34px rgba(219,125,52,.2)}
.achievements-entry strong{display:block;font-size:21px;margin-bottom:4px}.achievements-entry span span{opacity:.82}.achievements-entry b{font-size:22px;background:rgba(255,255,255,.76);padding:8px 13px;border-radius:13px;white-space:nowrap}
.achievements-screen{display:none;max-width:1120px;margin:0 auto;padding:28px 24px 64px}.achievements-screen.open{display:block}
.achievement-summary{display:grid;grid-template-columns:190px 1fr;gap:18px;margin:22px 0}.achievement-total,.achievement-progress-box{background:#fff;border:1px solid #e2dcf1;border-radius:24px;padding:23px;box-shadow:0 12px 30px rgba(78,64,140,.08)}
.achievement-total{display:grid;place-items:center;text-align:center}.achievement-total strong{font-size:42px;line-height:1;color:#5548c4}.achievement-total span{color:#747c96;margin-top:8px}.achievement-progress-box h2{margin:0 0 15px;font-size:20px}.achievement-line{margin:12px 0}.achievement-line div{display:flex;justify-content:space-between;gap:12px;margin-bottom:6px;font-weight:800;color:#4b526d}.achievement-track{display:block;height:10px;background:#ece8f5;border-radius:99px;overflow:hidden}.achievement-track i{display:block;height:100%;background:linear-gradient(90deg,#6c59df,#43acd9);border-radius:99px}
.achievement-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.achievement-card{position:relative;display:grid;grid-template-columns:58px 1fr;gap:15px;align-items:center;background:#fff;border:1px solid #e3ddf1;border-radius:20px;padding:19px;min-height:122px;box-shadow:0 10px 25px rgba(74,61,130,.07)}
.achievement-card.unlocked{border-color:#efc259;background:linear-gradient(130deg,#fffdf4,#fff7d7)}.achievement-card.locked{filter:saturate(.3);opacity:.7}.achievement-icon{width:58px;height:58px;display:grid;place-items:center;border-radius:18px;background:#eeeaf8;font-size:30px}.achievement-card.unlocked .achievement-icon{background:#ffe594;box-shadow:0 8px 18px rgba(222,166,46,.2)}
.achievement-card h3{margin:0 0 4px;font-size:17px;color:#303653}.achievement-card p{margin:0;color:#757c94;font-size:14px;line-height:1.4}.achievement-state{display:inline-block;margin-top:8px;font-size:12px;font-weight:900;color:#847d97}.achievement-card.unlocked .achievement-state{color:#a36300}.achievement-record{font-weight:900;color:#5548c4}
@media(max-width:700px){.achievements-screen{padding:20px 14px 48px}.achievement-summary{grid-template-columns:1fr}.achievement-grid{grid-template-columns:1fr}.achievements-entry{display:block}.achievements-entry b{display:inline-block;margin-top:12px}}
`;
document.head.appendChild(achievementStyles);
const achievementsScreen=document.createElement('main');achievementsScreen.className='achievements-screen';document.querySelector('.app').appendChild(achievementsScreen);
const achievementsEntry=document.createElement('button');achievementsEntry.className='achievements-entry';achievementsEntry.innerHTML='<span><strong>🏆 Мои достижения</strong><span>Награды за тренировки и пробные варианты</span></span><b id="homeAchievementCount" style="display:block;width:max-content;margin:12px auto 0;padding:12px 28px;border-radius:16px;background:#fff4df;color:#633600;font-size:28px;font-weight:900;text-align:center;">0 / 10</b>';home.appendChild(achievementsEntry);

function mockSectionValue(n,part){const teacher=part==='letter'?localStorage.getItem('oge-mock-'+n+'-letter-teacher'):part==='speaking'?localStorage.getItem('oge-mock-'+n+'-speaking-teacher'):null;if(teacher!==null)return Number(teacher);const key=part==='letter'?'letter-precheck':part==='speaking'?'speaking-precheck':part;const value=localStorage.getItem('oge-mock-'+n+'-'+key);return value===null?null:Number(value)}
function getCurrentStudent() {
  try {
    return JSON.parse(sessionStorage.getItem('englishup-student-session') || 'null');
  } catch (_) {
    return null;
  }
}
function getAchievementData(){
 const d=getProgressData(),trainingDone=d.completed.reduce((a,b)=>a+b,0),trainingTotal=d.available.reduce((a,b)=>a+b,0),fullTrainingSections=d.completed.filter((x,i)=>x>=d.available[i]).length,mockParts=['listening','reading','grammar','letter','speaking'],mockRows=[];for(let n=1;n<=10;n++){const values=mockParts.map(p=>mockSectionValue(n,p)),done=values.filter(v=>v!==null).length,total=values.reduce((s,v)=>s+(v===null?0:v),0);mockRows.push({n,values,done,total,complete:done===5})}const completed=mockRows.filter(x=>x.complete),best=completed.length?Math.max(...completed.map(x=>x.total)):0,uniqueScores=new Set(completed.map(x=>x.total)),anyMockPart=mockRows.some(x=>x.done>0);const items=[
{icon:'🌱',title:'Первый шаг',text:'Выполнить первую тренировку.',ok:trainingDone>=1,state:trainingDone>=1?'Получено':'Начни любую тренировку'},
{icon:'⚡',title:'Половина пути',text:'Пройти не менее половины всех тренировок.',ok:trainingDone>=Math.ceil(trainingTotal/2),state:trainingDone+' из '+trainingTotal},
{icon:'🎯',title:'Раздел закрыт',text:'Полностью пройти один тренировочный раздел.',ok:fullTrainingSections>=1,state:fullTrainingSections+' из 5 разделов'},
{icon:'👑',title:'Мастер тренировок',text:'Завершить все тренировочные разделы.',ok:trainingTotal>0&&trainingDone>=trainingTotal,state:trainingDone+' из '+trainingTotal},
{icon:'🚩',title:'Знакомство с пробником',text:'Выполнить первый раздел любого пробного варианта.',ok:anyMockPart,state:anyMockPart?'Получено':'Выполни один раздел'},
{icon:'🥉',title:'Первый пробник',text:'Полностью пройти один вариант ОГЭ.',ok:completed.length>=1,state:completed.length+' из 10'},
{icon:'🥈',title:'Половина пробников',text:'Полностью пройти 5 вариантов ОГЭ.',ok:completed.length>=5,state:completed.length+' из 10'},
{icon:'🏆',title:'Все 10 вариантов',text:'Полностью пройти десять пробных ОГЭ.',ok:completed.length>=10,state:completed.length+' из 10'},
{icon:'⭐',title:'Лучший результат',text:'Завершить пробник и сохранить свой лучший балл.',ok:completed.length>=1,state:completed.length?('Рекорд: '+best+' / 68'):'Заверши первый пробник'},
{icon:'🚀',title:'Новый личный рекорд',text:'Улучшить результат в следующем полном пробнике.',ok:uniqueScores.size>=2,state:uniqueScores.size>=2?('Лучший: '+best+' / 68'):'Нужны два разных результата'}
];return{d,trainingDone,trainingTotal,completed:completed.length,best,items,unlocked:items.filter(x=>x.ok).length}}
function renderAchievements(){const a=getAchievementData(),trainingPct=a.trainingTotal?Math.round(a.trainingDone/a.trainingTotal*100):0,mockPct=Math.round(a.completed/10*100);achievementsScreen.innerHTML='<button class="back-home" id="achievementsBack">← Все разделы</button><section class="reading-head"><div><span class="home-kicker">🏆 Награды</span><h1>Мои достижения</h1><p>Значки открываются автоматически по мере выполнения заданий</p></div><div class="score-badge"><span>Открыто</span><strong>'+a.unlocked+' / 10</strong></div></section><div class="achievement-summary"><div class="achievement-total"><strong>'+a.unlocked+'</strong><span>наград получено</span></div><div class="achievement-progress-box"><h2>Путь к цели</h2><div class="achievement-line"><div><span>Тренировки</span><b>'+a.trainingDone+' / '+a.trainingTotal+'</b></div><span class="achievement-track"><i style="width:'+trainingPct+'%"></i></span></div><div class="achievement-line"><div><span>Полные пробники</span><b>'+a.completed+' / 10</b></div><span class="achievement-track"><i style="width:'+mockPct+'%"></i></span></div>'+(a.best?'<div class="achievement-record">Лучший пробник: '+a.best+' из 68</div>':'')+'</div></div><div class="achievement-grid">'+a.items.map(x=>'<article class="achievement-card '+(x.ok?'unlocked':'locked')+'"><div class="achievement-icon">'+(x.ok?x.icon:'🔒')+'</div><div><h3>'+x.title+'</h3><p>'+x.text+'</p><span class="achievement-state">'+(x.ok?'✓ ':'')+x.state+'</span></div></article>').join('')+'</div>';document.getElementById('achievementsBack').onclick=closeAchievements;window.scrollTo({top:0,behavior:'smooth'})}
function openAchievements(){home.style.display='none';[trainerShell,grammarScreen,readingScreen,listeningScreen,speakingScreen,resultsScreen,mockScreen].forEach(x=>x.classList.remove('open'));achievementsScreen.classList.add('open');setSectionLabel('Мои достижения','Достижения');renderAchievements()}
function closeAchievements(){achievementsScreen.classList.remove('open');home.style.display='block';setSectionLabel('Разделы ОГЭ','Главная');updateHomeAchievements();window.scrollTo({top:0,behavior:'smooth'})}
function updateHomeAchievements(){const a=getAchievementData(),el=document.getElementById('homeAchievementCount');if(el)el.textContent=a.unlocked+' / 10'}
achievementsEntry.onclick=openAchievements;document.addEventListener('click',()=>setTimeout(updateHomeAchievements,0));document.addEventListener('change',()=>setTimeout(updateHomeAchievements,0));updateHomeAchievements();
